### ISSUE TITLE
There is an issue with this theme in doom emacs modal line

### ISSUE THREAD

**Issue by ujjwal3067** [nickav/naysayer-theme.el#5]
everything is fine except the file path in modal line. ( below ). Issue is the bright green color makes it impossible to view the file path. It's even worse when you work with projectile ( long path names ) it's displays is bright pink
![Screen Shot 2021-02-25 at 9 16 03 PM](https://user-images.githubusercontent.com/28984548/109245540-acad8580-77ae-11eb-9cdc-9f0be716428f.png)

**Comment by edibotopic** [comment]
Hi @ujjwal3067 , I'm not sure if you ever fixed this but I ran into some similar issues recently and thought I would provide some input here.

I am using Doom Emacs (you might be too?) and I believe it has some of its own modeline configurations. For example, the bright green colour of the directory can be set to the same as the filename (legible) if you add this line to the naysayer theme config:

```elisp
   `(doom-modeline-project-dir ((t (:weight bold))))
```
For the record: I found `doom-modeline-project-dir` and its associated colour by running `M-x list-faces display`.
I assume @nickav did not set this in the theme definition because he did not (and perhaps should not) consider the specifics of Emacs distributions (like Doom, Spacemacs, etc.). As it is not set explicitly Doom takes the colour setting for Strings in naysayer and applies it to the project dir.
You could either change `doom-modeline-project-dir` in your own local setup or create/request a Doom-specific version of the theme.
If the line above was added to the theme config I don't know if it would affect its performance on Vanilla Emacs - if it did not then perhaps it could be added in a ";;Doom-specific parameters" section (I can't test this currently).

Lastly, I don't think I am using projectile (I am not a routine Emacs user) but I have a similar issue with the whole path becoming bright pink, mainly when a buffer has unsaved edits, which happens a lot. Adding the line below to the theme stops this:

```elisp
   `(error ((t (:weight normal))))
```

Now when there is unsaved changes the colour of the text will stay the same but the weight will change from **bold** to normal.
On Doom Emacs at least, the change in colour when a buffer has unsaved edits seems to be attached to `error` and if it is not styled/coloured explicitly it seems to inherit a pink colour from somewhere else.

I think this second line can/should be added directly to the naysayer theme definition because it is not Doom-specific and the default pink colour makes the modeline illegible against the tan background. @nickav - I'm not sure if you're maintaining this actively but I could submit a PR for this if you want.

**Comment by nickav** [comment]
@edibotopic - you are correct, i am not actively maintaining this project but am happy to accept PRs!

**Comment by edibotopic** [comment]
OK @nickav - I will have a look in a few days and put through a PR. Thanks for the theme by the way.
